### ISSUE TITLE
Which dependencies did you support the Angular Univesal in the package.json ?

### ISSUE THREAD

**Issue by qqaimh** [ashokvishwakarma/koa-cart#1]
I am using koa2 with Angular, I saw you article in Medium.(https://medium.com/@avishwakarma/server-side-rendering-using-koajs-and-angular-universal-9270fe182f41).
I want to know that which package support koa just like @nguniversal/express-engine support express?

**Comment by avishwakarma** [comment]
On that article, I have created a utility to get the job done you can find the same on below link https://gist.github.com/ashokvishwakarma/7c97578108e49fb38d06777e8319bb24
